#!/bin/sh
# Language-agnostic interop matrix.
#
# The harness knows nothing about any specific implementation. It discovers
# drivers in interop/drivers/*.sh, each of which speaks the neutral driver
# contract (see README.md), and runs every (responder, initiator) pair: one
# driver listens as node "one", the other connects as node "two" and sends a
# message, and the harness checks the message arrived. A client does not care
# what implementation answers, only that the protocol is obeyed.
#
# Adding an implementation is dropping a new drivers/<name>.sh — no change here.
#
# Requires the shared mesh to be provisioned first (a root and two member
# certificates); this uses the bundled bonemesh-ca, whose output is neutral and
# consumed identically by every driver. Exits non-zero if any pair fails.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/.." && pwd)
cabin="$repo/go/bonemesh-ca"
mesh="interop-mesh"
work=$(mktemp -d)
trap 'rm -rf "$work"; kill $(jobs -p) 2>/dev/null || true' EXIT

ca() { "$cabin" "$@" >/dev/null 2>&1; }

echo "provisioning the mesh root"
# Prefer the pinned go126 toolchain when present, as the drivers and the
# helper builds above already do; the developer driver has no bare "go".
sh "$here/ensure-bin.sh" go bonemesh-ca
ca init-root --out "$work/ca"
# The payload is deliberately larger than the 64 KiB transport frame cap, so every
# cell exercises origin-side splitting and destination-side reassembly (protocol.md
# 6.1) as well as the handshake. Before 3.3.0 every payload in every tier was a
# sub-100-byte probe, which is exactly why defect D11 -- five of seven ports unable to
# send an oversized payload at all, and two delivering fragments to the application as
# though they were whole messages -- was invisible to the entire battery.
#
# Two markers, one at each end, rather than one. That is what lets a single send tell
# the three outcomes apart:
#
#   both markers  -> the payload was split and fully reassembled
#   head only     -> a fragment reached the application (the D11 corruption)
#   neither       -> delivery or the handshake failed
#
# A second small-payload pass would cost 49 more cells of wall clock and still could
# not distinguish the middle case.
#
# The listener window and the delivery poll below were widened when this payload grew:
# 96 KB across five frames takes meaningfully longer than the 40-byte probe they were
# sized for, and on a loaded host the slowest pair (PHP initiating, which has no
# background loop and must pump its own writes) came in just past the old 20 s / 6 s
# budget. Only the budget moved -- the oracle still demands BOTH markers, so a pair
# that delivers nothing, or delivers a fragment, still fails. This is the D12 lesson
# applied before it bit: a window that has to absorb both startup and a large transfer
# needs to be sized for the transfer, not for the probe it replaced.
head_marker="cross-language-hello"
tail_marker="reassembled-intact"
# 96000 filler characters: four segments at the pinned 24000-byte maximum, so the
# multi-segment path runs rather than the single-cut boundary case.
filler=$(yes 0123456789abcdef | head -6000 | tr -d '\n')
printf '{"head":"%s","filler":"%s","tail":"%s"}' \
  "$head_marker" "$filler" "$tail_marker" > "$work/message.json"
# Prove the payload really is over the cap before trusting any PASS it produces: a
# silently-small payload would turn all 49 cells back into the pre-3.3.0 no-op.
size=$(wc -c < "$work/message.json")
if [ "$size" -le 65536 ]; then
  echo "matrix payload is only $size bytes; it must exceed the 65536-byte transport cap" >&2
  exit 1
fi

# Issues a member certificate for a node whose identity was generated by its own
# driver. Each node makes its own private key in its own format (never shared);
# the CA signs only the public key, so the mesh is truly implementation-agnostic.
issue_for() {
  driver="$1"; label="$2"
  "$here/drivers/$driver.sh" keygen --id-pub "$work/$label.pub" --id-priv "$work/$label.priv"
  ca issue --root-priv "$work/ca/root.priv" --root-pub "$work/ca/root.pub" \
    --mesh "$mesh" --label "$label" --key "$work/$label.pub" --days 1 --out "$work/$label.cert.json"
}

# Discover implementations from the driver directory, then keep only those whose
# toolchain is actually present on this host — each skip is logged, never silent,
# so a host missing a runtime (e.g. no Erlang/OTP 28) narrows coverage visibly.
impls=""
for d in "$here"/drivers/*.sh; do
  impl=$(basename "$d" .sh)
  if "$d" keygen --id-pub "$work/probe.pub" --id-priv "$work/probe.priv" >/dev/null 2>&1 && [ -s "$work/probe.pub" ]; then
    impls="$impls $impl"
  else
    echo "SKIP $impl — toolchain unavailable on this host"
  fi
done
echo "implementations usable:$impls"

free_port() {
  p=34100
  while :; do
    if (exec 3<>/dev/tcp/127.0.0.1/$p) 2>/dev/null; then
      exec 3>&- 3<&-
      p=$((p + 1))
    else
      echo "$p"
      return
    fi
  done
}

# --- oracle self-test -------------------------------------------------------
#
# The two-marker oracle is only worth having if it actually separates the three
# outcomes, so feed it the output each broken system would produce and confirm it
# says the right thing. This runs in milliseconds and needs no mesh, so there is no
# excuse for the oracle below being unmeasured.
#
# The fragment case is the one that matters and the one a single-marker oracle gets
# wrong: a port that hands the application the first segment writes a line that DOES
# contain the head marker, because "head" is the first member of the payload JSON.
classify_out() {
  # Exactly the condition the pair loop uses, extracted so both can be read together.
  if grep -q "$tail_marker" "$1" 2>/dev/null && grep -q "$head_marker" "$1" 2>/dev/null; then
    echo reassembled
  elif grep -q "$head_marker" "$1" 2>/dev/null; then
    echo fragment
  else
    echo undelivered
  fi
}

if [ "${1:-}" = "--self-test" ]; then
  t=$(mktemp -d)
  trap 'rm -rf "$t"' EXIT
  bad=0

  cp "$work/message.json" "$t/whole.txt"
  head -c 24000 "$work/message.json" > "$t/fragment.txt"
  printf 'null\nnull\n' > "$t/nulls.txt"
  : > "$t/empty.txt"

  expect() {
    got=$(classify_out "$t/$1")
    if [ "$got" = "$2" ]; then
      echo "self-test ok: $1 -> $2"
    else
      echo "self-test FAIL: $1 classified as $got, expected $2" >&2
      bad=$((bad + 1))
    fi
  }
  expect whole.txt reassembled
  expect fragment.txt fragment
  expect nulls.txt undelivered
  expect empty.txt undelivered

  if [ "$bad" -ne 0 ]; then
    echo "the matrix oracle does not separate the outcomes it claims to" >&2
    exit 1
  fi
  echo "matrix oracle: separates reassembled / fragment / undelivered"
  exit 0
fi

fail=0
results=""

for server in $impls; do
  for client in $impls; do
    port=$(free_port)
    out="$work/received-$server-$client.txt"
    : > "$out"

    # Each side generates its own identity with its own driver; the CA issues a
    # certificate over each public key.
    issue_for "$server" one
    issue_for "$client" two

    # "one" listens (responder) via the server driver.
    "$here/drivers/$server.sh" listen --port "$port" --mesh "$mesh" \
      --root-pub "$work/ca/root.pub" --cert "$work/one.cert.json" \
      --id-pub "$work/one.pub" --id-priv "$work/one.priv" --out "$out" --seconds 35 &
    server_pid=$!

    # Wait for the listener to bind.
    tries=0
    while ! (exec 3<>/dev/tcp/127.0.0.1/$port) 2>/dev/null; do
      tries=$((tries + 1)); [ "$tries" -gt 100 ] && break; sleep 0.1
    done
    exec 3>&- 3<&- 2>/dev/null || true

    # "two" connects (initiator) via the client driver and sends to "one".
    "$here/drivers/$client.sh" connect --mesh "$mesh" \
      --root-pub "$work/ca/root.pub" --cert "$work/two.cert.json" \
      --id-pub "$work/two.pub" --id-priv "$work/two.priv" \
      --host 127.0.0.1 --port "$port" --to one --message "$work/message.json" --seconds 12 \
      >/dev/null 2>&1 || true

    # Give delivery a moment, then classify. Both markers must be present: the tail
    # is what proves reassembly completed rather than a fragment being handed up.
    # classify_out is the SAME function the --self-test exercises; duplicating the
    # condition here would have left the self-test checking a copy of the oracle
    # rather than the oracle.
    ok=no
    tries=0
    while [ "$tries" -lt 60 ]; do
      verdict=$(classify_out "$out")
      if [ "$verdict" = reassembled ]; then ok=yes; break; fi
      tries=$((tries + 1)); sleep 0.2
    done
    # Name which of the three outcomes it was, so a failure is diagnosable.
    if [ "$ok" = no ] && [ "$verdict" = fragment ]; then
      echo "  responder=$server initiator=$client: a FRAGMENT was delivered (D11)" >&2
    fi

    kill "$server_pid" 2>/dev/null || true
    wait "$server_pid" 2>/dev/null || true

    if [ "$ok" = yes ]; then
      results="$results\nPASS  responder=$server  initiator=$client"
    else
      results="$results\nFAIL  responder=$server  initiator=$client"
      fail=1
    fi
  done
done

printf '%b\n' "$results"
if [ "$fail" -ne 0 ]; then
  echo "interop matrix: FAILURES present"
  exit 1
fi
echo "interop matrix: all pairs interoperate"
